// Generated by gencpp from file robot_tutorials/maxTwoIntsResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_TUTORIALS_MESSAGE_MAXTWOINTSRESPONSE_H
#define ROBOT_TUTORIALS_MESSAGE_MAXTWOINTSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_tutorials
{
template <class ContainerAllocator>
struct maxTwoIntsResponse_
{
  typedef maxTwoIntsResponse_<ContainerAllocator> Type;

  maxTwoIntsResponse_()
    : max(0)  {
    }
  maxTwoIntsResponse_(const ContainerAllocator& _alloc)
    : max(0)  {
  (void)_alloc;
    }



   typedef int64_t _max_type;
  _max_type max;





  typedef boost::shared_ptr< ::robot_tutorials::maxTwoIntsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_tutorials::maxTwoIntsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct maxTwoIntsResponse_

typedef ::robot_tutorials::maxTwoIntsResponse_<std::allocator<void> > maxTwoIntsResponse;

typedef boost::shared_ptr< ::robot_tutorials::maxTwoIntsResponse > maxTwoIntsResponsePtr;
typedef boost::shared_ptr< ::robot_tutorials::maxTwoIntsResponse const> maxTwoIntsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_tutorials::maxTwoIntsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_tutorials::maxTwoIntsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'robot_tutorials': ['/mnt/d/personal/ROS/wallE_ws/src/robot_tutorials/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot_tutorials::maxTwoIntsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_tutorials::maxTwoIntsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_tutorials::maxTwoIntsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_tutorials::maxTwoIntsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_tutorials::maxTwoIntsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_tutorials::maxTwoIntsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_tutorials::maxTwoIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1978653de1814b9f74fe866ab7d0d762";
  }

  static const char* value(const ::robot_tutorials::maxTwoIntsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1978653de1814b9fULL;
  static const uint64_t static_value2 = 0x74fe866ab7d0d762ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_tutorials::maxTwoIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_tutorials/maxTwoIntsResponse";
  }

  static const char* value(const ::robot_tutorials::maxTwoIntsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_tutorials::maxTwoIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 max\n\
";
  }

  static const char* value(const ::robot_tutorials::maxTwoIntsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_tutorials::maxTwoIntsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.max);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct maxTwoIntsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_tutorials::maxTwoIntsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_tutorials::maxTwoIntsResponse_<ContainerAllocator>& v)
  {
    s << indent << "max: ";
    Printer<int64_t>::stream(s, indent + "  ", v.max);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_TUTORIALS_MESSAGE_MAXTWOINTSRESPONSE_H
