// Generated by gencpp from file robot_tutorials/maxTwoInts.msg
// DO NOT EDIT!


#ifndef ROBOT_TUTORIALS_MESSAGE_MAXTWOINTS_H
#define ROBOT_TUTORIALS_MESSAGE_MAXTWOINTS_H

#include <ros/service_traits.h>


#include <robot_tutorials/maxTwoIntsRequest.h>
#include <robot_tutorials/maxTwoIntsResponse.h>


namespace robot_tutorials
{

struct maxTwoInts
{

typedef maxTwoIntsRequest Request;
typedef maxTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct maxTwoInts
} // namespace robot_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_tutorials::maxTwoInts > {
  static const char* value()
  {
    return "0ed8b4b501f348884acc82d51e666664";
  }

  static const char* value(const ::robot_tutorials::maxTwoInts&) { return value(); }
};

template<>
struct DataType< ::robot_tutorials::maxTwoInts > {
  static const char* value()
  {
    return "robot_tutorials/maxTwoInts";
  }

  static const char* value(const ::robot_tutorials::maxTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::robot_tutorials::maxTwoIntsRequest> should match 
// service_traits::MD5Sum< ::robot_tutorials::maxTwoInts > 
template<>
struct MD5Sum< ::robot_tutorials::maxTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_tutorials::maxTwoInts >::value();
  }
  static const char* value(const ::robot_tutorials::maxTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_tutorials::maxTwoIntsRequest> should match 
// service_traits::DataType< ::robot_tutorials::maxTwoInts > 
template<>
struct DataType< ::robot_tutorials::maxTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::robot_tutorials::maxTwoInts >::value();
  }
  static const char* value(const ::robot_tutorials::maxTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_tutorials::maxTwoIntsResponse> should match 
// service_traits::MD5Sum< ::robot_tutorials::maxTwoInts > 
template<>
struct MD5Sum< ::robot_tutorials::maxTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_tutorials::maxTwoInts >::value();
  }
  static const char* value(const ::robot_tutorials::maxTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_tutorials::maxTwoIntsResponse> should match 
// service_traits::DataType< ::robot_tutorials::maxTwoInts > 
template<>
struct DataType< ::robot_tutorials::maxTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::robot_tutorials::maxTwoInts >::value();
  }
  static const char* value(const ::robot_tutorials::maxTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_TUTORIALS_MESSAGE_MAXTWOINTS_H
